// GENERATED by scripts/make-reference-cases.mjs. Do not edit by hand.
//
// Real kidneys from the KiTS23 reference labels, meshed by the pipeline and
// republished here under neutral letters. Every number below was computed by
// renalplan from the geometry and copied out of that case's planning.json.
// KiTS23 is used under CC BY-NC-SA 4.0.

export type ReferenceStructure = {
  name: string;
  label: string;
  colour: string;
  opacity: number;
  visible: boolean;
};

export type ReferenceCase = {
  id: string;
  label: string;
  mesh: string;
  structures: ReferenceStructure[];
  nephrometry: {
    renalLabel: string;
    renalTotal: number;
    renalComplexity: string;
    paduaTotal: number;
    paduaComplexity: string;
    radiusCm: number;
    exophyticFraction: number;
    nearnessMm: number;
    face: string;
    polarLocation: string;
    rim: string;
    locationDetail: string;
    hilar: boolean;
  };
  runtimeSeconds: number;
};

export const referenceCases: ReferenceCase[] = [
  {
    "id": "reference-a",
    "label": "Reference kidney A",
    "mesh": "/models/reference-a.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true
      }
    ],
    "nephrometry": {
      "renalLabel": "5p",
      "renalTotal": 5,
      "renalComplexity": "low",
      "paduaTotal": 7,
      "paduaComplexity": "low",
      "radiusCm": 3.11,
      "exophyticFraction": 0.226,
      "nearnessMm": 39.8,
      "face": "p",
      "polarLocation": "inferior",
      "rim": "lateral",
      "locationDetail": "entirely above or below the polar lines",
      "hilar": false
    },
    "runtimeSeconds": 46.7
  },
  {
    "id": "reference-b",
    "label": "Reference kidney B",
    "mesh": "/models/reference-b.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true
      }
    ],
    "nephrometry": {
      "renalLabel": "10a",
      "renalTotal": 10,
      "renalComplexity": "high",
      "paduaTotal": 10,
      "paduaComplexity": "high",
      "radiusCm": 2.58,
      "exophyticFraction": 0,
      "nearnessMm": 1.1,
      "face": "a",
      "polarLocation": "middle",
      "rim": "medial",
      "locationDetail": "entirely between the polar lines",
      "hilar": false
    },
    "runtimeSeconds": 77.2
  },
  {
    "id": "reference-c",
    "label": "Reference kidney C",
    "mesh": "/models/reference-c.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true
      },
      {
        "name": "cyst",
        "label": "Cyst",
        "colour": "#8fb8d8",
        "opacity": 0.7,
        "visible": true
      },
      {
        "name": "ribs",
        "label": "Ribs",
        "colour": "#d8d2c4",
        "opacity": 0.5,
        "visible": false
      },
      {
        "name": "psoas",
        "label": "Psoas",
        "colour": "#b98b7a",
        "opacity": 0.45,
        "visible": false
      },
      {
        "name": "colon",
        "label": "Colon",
        "colour": "#c8a06a",
        "opacity": 0.45,
        "visible": false
      },
      {
        "name": "spleen",
        "label": "Spleen",
        "colour": "#a8737d",
        "opacity": 0.45,
        "visible": false
      },
      {
        "name": "liver",
        "label": "Liver",
        "colour": "#9d7a6b",
        "opacity": 0.4,
        "visible": false
      },
      {
        "name": "skin",
        "label": "Body outline",
        "colour": "#8fa0ad",
        "opacity": 0.09,
        "visible": false
      }
    ],
    "nephrometry": {
      "renalLabel": "8p",
      "renalTotal": 8,
      "renalComplexity": "moderate",
      "paduaTotal": 9,
      "paduaComplexity": "intermediate",
      "radiusCm": 4.9,
      "exophyticFraction": 0.282,
      "nearnessMm": 36.1,
      "face": "p",
      "polarLocation": "middle",
      "rim": "lateral",
      "locationDetail": "crosses the axial renal midline",
      "hilar": false
    },
    "runtimeSeconds": 30.1
  },
  {
    "id": "reference-d",
    "label": "Reference kidney D",
    "mesh": "/models/reference-d.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true
      }
    ],
    "nephrometry": {
      "renalLabel": "6x",
      "renalTotal": 6,
      "renalComplexity": "low",
      "paduaTotal": 8,
      "paduaComplexity": "intermediate",
      "radiusCm": 3.25,
      "exophyticFraction": 0.025,
      "nearnessMm": 27.3,
      "face": "x",
      "polarLocation": "inferior",
      "rim": "lateral",
      "locationDetail": "entirely above or below the polar lines",
      "hilar": false
    },
    "runtimeSeconds": 23.6
  },
  {
    "id": "reference-e",
    "label": "Reference kidney E",
    "mesh": "/models/reference-e.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true
      }
    ],
    "nephrometry": {
      "renalLabel": "7x",
      "renalTotal": 7,
      "renalComplexity": "moderate",
      "paduaTotal": 9,
      "paduaComplexity": "intermediate",
      "radiusCm": 4.26,
      "exophyticFraction": 0.163,
      "nearnessMm": 28.2,
      "face": "x",
      "polarLocation": "middle",
      "rim": "lateral",
      "locationDetail": "crosses a polar line",
      "hilar": false
    },
    "runtimeSeconds": 3.2
  }
];

export const referenceCaseCount = 5;
