// GENERATED by scripts/make-reference-cases.mjs. Do not edit by hand.
//
// Five KiTS23 kidneys, republished under neutral letters. The meshes were
// copied from my separate CalyxView endourology project, which built them from
// the same KiTS23 expert outlines. Kidney C's surrounding organs are
// TotalSegmentator (AI) outlines of the CT and haven't been checked. The
// nephrometry was computed by renalplan from the KiTS23 label maps, not from
// these meshes, and the display values match the pipeline table on the site.
// KiTS23 imaging and labels are CC BY-NC-SA 4.0.

export type ReferenceStructure = {
  name: string;
  label: string;
  /** Where the outline came from, shown under the layer name. */
  provenance: string;
  colour: string;
  opacity: number;
  visible: boolean;
  /** Whether the camera frames on this structure. */
  framing: boolean;
};

export type ReferenceCase = {
  id: string;
  label: string;
  mesh: string;
  structures: ReferenceStructure[];
  nephrometry: {
    renalLabel: string;
    renalTotal: number;
    renalComplexity: string;
    /** The R.E.N.A.L. points that make up renalTotal. */
    renalPoints: { r: number; e: number; n: number; l: number };
    paduaTotal: number;
    paduaComplexity: string;
    /** PADUA's renal-sinus item, against the estimated sinus. */
    paduaSinusInvolved: boolean;
    /** Largest tumour diameter, 1 dp, as in the pipeline table. */
    diameterCm: number;
    tumourMl: number;
    exophyticFraction: number;
    /** Tumour to the estimated renal sinus, which sets N. */
    nearnessMm: number;
    /** Share of the tumour-side kidney outside a uniform 5 mm band round the tumour. */
    preservedFraction: number;
    face: string;
    polarLocation: string;
    rim: string;
    locationDetail: string;
    /** Only meaningful when hilarAssessed is true. */
    hilar: boolean;
    /** The sinus estimate was too small or off-centre, so the polar lines were put where 30% of the kidney's volume lies beyond each. */
    polarLinesAssumed: boolean;
    /** The sinus estimate was far too big for a renal sinus, so the kidney isn't the usual shape. */
    sinusEstimateTooLarge: boolean;
    hilarAssessed: boolean;
    collectingAssessed: boolean;
  };
  caseNotes: string[];
  runtimeSeconds: number;
};

export const referenceCases: ReferenceCase[] = [
  {
    "id": "reference-a",
    "label": "Kidney A",
    "mesh": "/models/reference-a.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "provenance": "KiTS expert outline",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true,
        "framing": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "provenance": "KiTS expert outline",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true,
        "framing": true
      }
    ],
    "nephrometry": {
      "renalLabel": "6p",
      "renalTotal": 6,
      "renalComplexity": "low",
      "renalPoints": {
        "r": 1,
        "e": 2,
        "n": 1,
        "l": 2
      },
      "paduaTotal": 7,
      "paduaComplexity": "low",
      "paduaSinusInvolved": false,
      "diameterCm": 3.1,
      "tumourMl": 8.7,
      "exophyticFraction": 0.226,
      "nearnessMm": 39.8,
      "preservedFraction": 0.958,
      "face": "p",
      "polarLocation": "inferior",
      "rim": "lateral",
      "locationDetail": "crosses a polar line",
      "hilar": false,
      "polarLinesAssumed": true,
      "sinusEstimateTooLarge": false,
      "hilarAssessed": false,
      "collectingAssessed": false
    },
    "caseNotes": [
      "The estimated sinus came out too small, or off to one side of the kidney's middle, to set the polar lines. So the pipeline put them where 30% of the kidney's volume lies beyond each, roughly a third and two thirds of the way along. That makes L and the PADUA pole rougher than usual. N and PADUA's rim and sinus items still use the small estimate, so they're approximate too, and N may read long."
    ],
    "runtimeSeconds": 11.6
  },
  {
    "id": "reference-b",
    "label": "Kidney B",
    "mesh": "/models/reference-b.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "provenance": "KiTS expert outline",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true,
        "framing": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "provenance": "KiTS expert outline",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true,
        "framing": true
      }
    ],
    "nephrometry": {
      "renalLabel": "10a",
      "renalTotal": 10,
      "renalComplexity": "high",
      "renalPoints": {
        "r": 1,
        "e": 3,
        "n": 3,
        "l": 3
      },
      "paduaTotal": 10,
      "paduaComplexity": "high",
      "paduaSinusInvolved": false,
      "diameterCm": 2.6,
      "tumourMl": 2.9,
      "exophyticFraction": 0,
      "nearnessMm": 1.1,
      "preservedFraction": 0.968,
      "face": "a",
      "polarLocation": "middle",
      "rim": "medial",
      "locationDetail": "entirely between the polar lines",
      "hilar": false,
      "polarLinesAssumed": false,
      "sinusEstimateTooLarge": false,
      "hilarAssessed": false,
      "collectingAssessed": false
    },
    "caseNotes": [
      "The KiTS outline has a second, smaller piece labelled tumour, which may not be in this kidney and which this 3D model leaves out. The scores are for the larger one."
    ],
    "runtimeSeconds": 18.2
  },
  {
    "id": "reference-c",
    "label": "Kidney C",
    "mesh": "/models/reference-c.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "provenance": "KiTS expert outline",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true,
        "framing": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "provenance": "KiTS expert outline",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true,
        "framing": true
      },
      {
        "name": "cyst",
        "label": "Cyst (other kidney)",
        "provenance": "KiTS expert outline",
        "colour": "#8fb8d8",
        "opacity": 0.7,
        "visible": false,
        "framing": false
      },
      {
        "name": "ribs",
        "label": "Ribs (AI outline)",
        "provenance": "TotalSegmentator (AI), unchecked",
        "colour": "#d8d2c4",
        "opacity": 0.5,
        "visible": false,
        "framing": false
      },
      {
        "name": "psoas",
        "label": "Psoas (AI outline)",
        "provenance": "TotalSegmentator (AI), unchecked",
        "colour": "#b98b7a",
        "opacity": 0.45,
        "visible": false,
        "framing": false
      },
      {
        "name": "colon",
        "label": "Colon (AI outline)",
        "provenance": "TotalSegmentator (AI), unchecked",
        "colour": "#c8a06a",
        "opacity": 0.45,
        "visible": false,
        "framing": false
      },
      {
        "name": "spleen",
        "label": "Spleen (AI outline)",
        "provenance": "TotalSegmentator (AI), unchecked",
        "colour": "#a8737d",
        "opacity": 0.45,
        "visible": false,
        "framing": false
      },
      {
        "name": "liver",
        "label": "Liver (AI outline)",
        "provenance": "TotalSegmentator (AI), unchecked",
        "colour": "#9d7a6b",
        "opacity": 0.4,
        "visible": false,
        "framing": false
      },
      {
        "name": "skin",
        "label": "Body outline (AI)",
        "provenance": "TotalSegmentator (AI), unchecked",
        "colour": "#8fa0ad",
        "opacity": 0.09,
        "visible": false,
        "framing": false
      }
    ],
    "nephrometry": {
      "renalLabel": "8p",
      "renalTotal": 8,
      "renalComplexity": "moderate",
      "renalPoints": {
        "r": 2,
        "e": 2,
        "n": 1,
        "l": 3
      },
      "paduaTotal": 9,
      "paduaComplexity": "intermediate",
      "paduaSinusInvolved": false,
      "diameterCm": 4.9,
      "tumourMl": 37,
      "exophyticFraction": 0.282,
      "nearnessMm": 36.1,
      "preservedFraction": 0.936,
      "face": "p",
      "polarLocation": "middle",
      "rim": "lateral",
      "locationDetail": "crosses the axial renal midline",
      "hilar": false,
      "polarLinesAssumed": false,
      "sinusEstimateTooLarge": false,
      "hilarAssessed": false,
      "collectingAssessed": false
    },
    "caseNotes": [],
    "runtimeSeconds": 9
  },
  {
    "id": "reference-d",
    "label": "Kidney D",
    "mesh": "/models/reference-d.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "provenance": "KiTS expert outline",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true,
        "framing": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "provenance": "KiTS expert outline",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true,
        "framing": true
      }
    ],
    "nephrometry": {
      "renalLabel": "8x",
      "renalTotal": 8,
      "renalComplexity": "moderate",
      "renalPoints": {
        "r": 1,
        "e": 3,
        "n": 1,
        "l": 3
      },
      "paduaTotal": 9,
      "paduaComplexity": "intermediate",
      "paduaSinusInvolved": false,
      "diameterCm": 3.2,
      "tumourMl": 11.4,
      "exophyticFraction": 0.025,
      "nearnessMm": 27.3,
      "preservedFraction": 0.943,
      "face": "x",
      "polarLocation": "middle",
      "rim": "lateral",
      "locationDetail": "more than half between the polar lines",
      "hilar": false,
      "polarLinesAssumed": true,
      "sinusEstimateTooLarge": false,
      "hilarAssessed": false,
      "collectingAssessed": false
    },
    "caseNotes": [
      "The estimated sinus came out too small, or off to one side of the kidney's middle, to set the polar lines. So the pipeline put them where 30% of the kidney's volume lies beyond each, roughly a third and two thirds of the way along. That makes L and the PADUA pole rougher than usual. N and PADUA's rim and sinus items still use the small estimate, so they're approximate too, and N may read long."
    ],
    "runtimeSeconds": 7.6
  },
  {
    "id": "reference-e",
    "label": "Kidney E",
    "mesh": "/models/reference-e.glb",
    "structures": [
      {
        "name": "parenchyma",
        "label": "Kidney",
        "provenance": "KiTS expert outline",
        "colour": "#c9b79b",
        "opacity": 0.34,
        "visible": true,
        "framing": true
      },
      {
        "name": "tumour",
        "label": "Tumour",
        "provenance": "KiTS expert outline",
        "colour": "#d85c60",
        "opacity": 1,
        "visible": true,
        "framing": true
      }
    ],
    "nephrometry": {
      "renalLabel": "7x",
      "renalTotal": 7,
      "renalComplexity": "moderate",
      "renalPoints": {
        "r": 2,
        "e": 2,
        "n": 1,
        "l": 2
      },
      "paduaTotal": 8,
      "paduaComplexity": "intermediate",
      "paduaSinusInvolved": false,
      "diameterCm": 4.3,
      "tumourMl": 20.2,
      "exophyticFraction": 0.163,
      "nearnessMm": 28.2,
      "preservedFraction": 0.952,
      "face": "x",
      "polarLocation": "inferior",
      "rim": "lateral",
      "locationDetail": "crosses a polar line",
      "hilar": false,
      "polarLinesAssumed": false,
      "sinusEstimateTooLarge": false,
      "hilarAssessed": false,
      "collectingAssessed": false
    },
    "caseNotes": [],
    "runtimeSeconds": 1.6
  }
];

export const referenceCaseCount = 5;
